<a href="https://colab.research.google.com/github/trex99/DAVI/blob/main/3%EC%A3%BC%EC%B0%A8_Lecture_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 라이브러리(패키지) 관리 (설치, 삭제)

## 라이브러리 설치

- pip install 

## 라이브러리 삭제

- pip uninstall 

# numpy 패키지

## 설치

## 삭제

## 활용

In [2]:
# 패키지를 사용하기 위한 최초 1회 실행
import numpy as np

In [3]:
a_list = [1,2,3,4,5]
a1 = np.array(a_list)
a1

array([1, 2, 3, 4, 5])

In [4]:
import numpy as np
sample_list = [1, 2, 3]
np_array = np.array(sample_list)
print(np_array)
print(type(np_array))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
sample_list = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]
np_2d_array = np.array(sample_list, dtype='str')
print(np_2d_array)
print(type(np_2d_array))

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

np.arange(0,5) # array([0, 1, 2, 3, 4])

np.arange(1,11,2) # array([1, 3, 5, 7, 9])

np.zeros(4) # array([0., 0., 0., 0.])

np.ones(5) # array([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.])

In [7]:
import numpy as np

np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
import numpy as np

np.eye(1)

array([[1.]])

In [9]:
np.eye(2) 

array([[1., 0.],
       [0., 1.]])

In [10]:
np.full((3,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [11]:
a = [1,2]
a*10

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [13]:
import numpy as np

sample_size = 7
np.random.rand(sample_size)

array([0.69989923, 0.49792712, 0.88399238, 0.98830984, 0.53815402,
       0.7229909 , 0.30981259])

In [15]:
import numpy as np

# 평균 0, 표준편차 1을 가지는 표준 정규 분포에서 추출
sample_size = 7
data = np.random.randn(sample_size)
data

array([-0.61730514, -0.85247942,  0.22344648,  1.11522612, -0.10927258,
       -0.81843774, -0.04099113])

In [20]:
import numpy as np

# 3~9사이의 정수를 7개 추출
np.random.randint(3, 10, 7)

array([4, 4, 4, 7, 3, 7, 5])

In [21]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
arr.reshape(2, 3)
 

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
arr.shape, arr.reshape(2, 3).shape
 

((6,), (2, 3))

In [23]:
simple_array = np.array([1, 2, 3, 4])

simple_array.max()
#Returns 4

simple_array.min()
#Returns 1


simple_array.argmax()
#Returns 3

simple_array.argmin()
#Returns 0

 

0

In [24]:
arr = np.arange(4)
# 덧셈 (np.add)
2 + arr
#Returns array([2, 3, 4, 5])
arr + arr
#Returns array([0, 2, 4, 6])


arr = np.arange(4)
# 뺄셈 (np.subtract)
arr - 10
#Returns array([-10,  -9,  -8,  -7])
arr - arr
#Returns array([0, 0, 0, 0])


arr = np.arange(4)
# 곱셈 (np.multiply)
6 * arr
#Returns array([ 0,  6, 12, 18])
arr * arr
#Returns array([0, 1, 4, 9])

arr = np.arange(4)
# 나눗셈 (np.divide)
arr / 2
#Returns array([0. , 0.5, 1. , 1.5])
arr / arr
#Returns array([nan,  1.,  1.,  1.])

<ipython-input-24-b615ed3fe808>:28: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.])

In [25]:
# 제곱근 연산
arr = np.arange(4)
np.sqrt(arr)
# array([0.        , 1.        , 1.41421356, 1.73205081])

# 지수연산
arr = np.arange(4)
np.exp(arr)
# array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

# 삼각함수연산 (sine)
arr = np.arange(4)
np.sin(arr)
# array([0.        , 0.84147098, 0.90929743, 0.14112001])

# 삼각함수연산 (cosine)
arr = np.arange(4)
np.cos(arr)
# array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

# 삼각함수연산 (logarithm)
arr = np.arange(4)
np.log(arr)
# array([      -inf, 0.        , 0.69314718, 1.09861229])

# 반올림
arr = np.random.rand(5)
np.round(arr, 2)
# array([0.13, 0.05, 0.89, 0.7 , 0.91])

<ipython-input-25-ba16ec6e080d>:23: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([0.86, 0.53, 0.66, 0.44, 0.63])

In [26]:
# 2차원 인덱싱
mat = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])

print(mat)
print('-' * 20)
print(mat[0])
print('-' * 20)
print(mat[0][-1])
print('-' * 20)
print(mat[1:][:2])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
--------------------
[ 5 10 15]
--------------------
15
--------------------
[[20 25 30]
 [35 40 45]]


# pandas 패키지

## 설치

## 삭제

## 활용

In [27]:
import pandas as pd

In [28]:
import pandas as pd
sample_list = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
df1 = pd.DataFrame(sample_list)
display(df1)
df2 = pd.DataFrame(sample_list, columns=['no1', 'no2', 'no3'])
display(df2)
display(df2.values)


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

no1  no2  no3
0    1    2    3
1    4    5    6
2    7    8    9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
import pandas as pd
sample_list = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
df = pd.DataFrame(sample_list)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [30]:
sample_dict = {
    'col1': [11,12,13,14],
    'col2': [21,22,23,24],
    'col3': [31,32,33,34],
}
df = pd.DataFrame(sample_dict)
df

col1  col2  col3
0    11    21    31
1    12    22    32
2    13    23    33
3    14    24    34

In [31]:
pd.DataFrame(np.random.randn(6, 4))


0         1         2         3
0 -0.761631  1.776603 -0.215006  0.151980
1  0.397853 -2.141440  0.514846 -0.402075
2 -1.135043 -1.020822  0.541588 -2.009249
3  1.690196  4.049485  0.415828 -0.175368
4  0.764717  0.305315  1.079098 -0.556264
5  0.585268 -0.617754 -1.640340 -0.585035

In [32]:
df.reset_index(drop=True)

col1  col2  col3
0    11    21    31
1    12    22    32
2    13    23    33
3    14    24    34

In [33]:
df.columns = ['change_col1', 'change_col2', 'change_col3']
df

change_col1  change_col2  change_col3
0           11           21           31
1           12           22           32
2           13           23           33
3           14           24           34

In [35]:
df = df.add_prefix('ks_')
df

ks_change_col1  ks_change_col2  ks_change_col3
0              11              21              31
1              12              22              32
2              13              23              33
3              14              24              34

In [37]:
import pandas as pd
sample_dict = {
    'col1': [11,12,13,14],
    'col2': [21,22,23,24],
    'col3': [31,32,33,34],
}
df = pd.DataFrame(sample_dict)

df.loc[1] = [41, 51, 61] # 행 추가 방법

df = df.append({'col1': 41, 'col2': 51, 'col3': 61}, ignore_index=True) # 행 추가 다른 방법

df['col_sum'] = 0 # 열 추가 방법

df

col1  col2  col3  col_sum
0    11    21    31        0
1    41    51    61        0
2    13    23    33        0
3    14    24    34        0
4    41    51    61        0

In [38]:
import pandas as pd
sample_dict = {
    'col1': [11,12,13,14],
    'col2': [21,22,23,24],
    'col3': [31,32,33,34],
}
df = pd.DataFrame(sample_dict)
display(df)

df.loc[2] # 2번째 행 
df.loc[2:] # 2번째 행부터 끝까지
df.loc[:2] # 처음부터 2번째 행까지
df[df.col1 == 13] # 첫행이 13인 행
df.T # 트랜스포즈 효과 (행렬 뒤바꿈 변경, 전치)

# df

col1  col2  col3
0    11    21    31
1    12    22    32
2    13    23    33
3    14    24    34

0   1   2   3
col1  11  12  13  14
col2  21  22  23  24
col3  31  32  33  34

In [39]:
import pandas as pd
sample_dict = {
    'col1': [11,12,13,14],
    'col2': [21,22,23,24],
    'col3': [31,32,33,34],
}
df = pd.DataFrame(sample_dict)

# del df['col1']

df.drop(columns=['col2', 'col3'], axis=0, inplace=True)

df = df.drop([df.index[1]]) # index 기준으로 삭제

target_index = df[df.col1 == 13].index # 특정 데이터 조회결과에 따라 삭제
df = df.drop(target_index)

df

col1
0    11
3    14

In [40]:
import pandas as pd
sample_dict = {
    'col1': [11,12,13,14],
    'col2': [21,22,23,24],
    'col3': [31,32,33,34],
}
df = pd.DataFrame(sample_dict)

df.loc[1, 'col1'] = 99 # 행,렬접근으로 변경
df['col1'] = [91, 92, 93, 94] # 특정 열 전체 변경
df.loc[1] = [99, 99, 99] # 특정 행 전체 변경

df

col1  col2  col3
0    91    21    31
1    99    99    99
2    93    23    33
3    94    24    34

In [41]:
import pandas as pd
sample_dict = {
    'col1': [11,12,13,np.NaN],
    'col2': [21,None,23,24],
    'col3': [31,32,np.nan,34],
}
df = pd.DataFrame(sample_dict)

# df.isnull()
# df.notnull()

# df = df.fillna(value=99.99)

# df = df.dropna(how='any')
# df = df.dropna(how='all')

# df

In [42]:
import pandas as pd
sample_dict = {
    'col1': [11,22,22,24],
    'col2': [21,22,22,24],
    'col3': [31,22,22,34],
}
df = pd.DataFrame(sample_dict)

df.duplicated()
# df.duplicated(keep='first') # first, last, False

# df = df.drop_duplicates(keep='first') # first, last, False

# df

0    False
1    False
2     True
3    False
dtype: bool

In [43]:
import pandas as pd
sample_dict = {
    'col1': [22,22,33,14],
    'col2': [21,22,33,24],
    'col3': [11,12,56,67],
}
df = pd.DataFrame(sample_dict)

df.head()
df.tail()
df.shape
df.describe()

df.col1.value_counts()
df.col1.value_counts(normalize=True)

df.info()
df.info(verbose=True) # null 컬럼 출력

df['col1'].unique()
df['col1'].nunique()
df['col1'].isin([22,12])
df.loc[df['col1'].isin([22,12]), :]


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      int64
dtypes: int64(3)
memory usage: 224.0 bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      int64
dtypes: int64(3)
memory usage: 224.0 bytes


col1  col2  col3
0    22    21    11
1    22    22    12

# 문제해결 활용

- 타이타닉 데이터셋을 이용한 데이터 전처리
- 전처리 아이디어
- 전처리 아이디어를 실행하기 위한 pandas 패키지 활용


&nbsp;&nbsp;  ⚓ https://www.kaggle.com/competitions/titanic

In [44]:
import pandas as pd
titanic = pd.read_csv('titanic.csv')
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [45]:
titanic = titanic.drop(columns=['PassengerId'], axis=0)
titanic

Survived  Pclass                                               Name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886         0       2                              Montvila, Rev. Juozas   
887         1       1                       Graham, Miss. Margaret Edith   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"   
889         1       1                              Behr, Mr. Karl Howell   
890         0       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [46]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Name      891 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Ticket    891 non-null    object 
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object 
 10  Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB


In [47]:
titanic = titanic.dropna()
titanic

Survived  Pclass                                               Name  \
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
6           0       1                            McCarthy, Mr. Timothy J   
10          1       3                    Sandstrom, Miss. Marguerite Rut   
11          1       1                           Bonnell, Miss. Elizabeth   
..        ...     ...                                                ...   
871         1       1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
872         0       1                           Carlsson, Mr. Frans Olof   
879         1       1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
887         1       1                       Graham, Miss. Margaret Edith   
889         1       1                              Behr, Mr. Karl Howell   

        Sex   Age  SibSp  Parch    Ticket     Fare        Cabin Embarked  
1    female  38.0      1      0  PC 17599  71.2833          C85        C  
3    female  35.0      1      0    113803  53.1000         C123        S  
6      male  54.0      0      0     17463  51.8625          E46        S  
10   female   4.0      1      1   PP 9549  16.7000           G6        S  
11   female  58.0      0      0    113783  26.5500         C103        S  
..      ...   ...    ...    ...       ...      ...          ...      ...  
871  female  47.0      1      1     11751  52.5542          D35        S  
872    male  33.0      0      0       695   5.0000  B51 B53 B55        S  
879  female  56.0      0      1     11767  83.1583          C50        C  
887  female  19.0      0      0    112053  30.0000          B42        S  
889    male  26.0      0      0    111369  30.0000         C148        C  

[183 rows x 11 columns]

In [48]:
titanic[titanic.duplicated()]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [49]:
titanic.Embarked.value_counts()

S    116
C     65
Q      2
Name: Embarked, dtype: int64

In [50]:
map_value = {'S': 0, 'C': 1, 'Q': 2}
titanic['Embarked'] = titanic.Embarked.map(map_value)
titanic

<ipython-input-50-c605a5e5adb1>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic['Embarked'] = titanic.Embarked.map(map_value)


Survived  Pclass                                               Name  \
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
6           0       1                            McCarthy, Mr. Timothy J   
10          1       3                    Sandstrom, Miss. Marguerite Rut   
11          1       1                           Bonnell, Miss. Elizabeth   
..        ...     ...                                                ...   
871         1       1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
872         0       1                           Carlsson, Mr. Frans Olof   
879         1       1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
887         1       1                       Graham, Miss. Margaret Edith   
889         1       1                              Behr, Mr. Karl Howell   

        Sex   Age  SibSp  Parch    Ticket     Fare        Cabin  Embarked  
1    female  38.0      1      0  PC 17599  71.2833          C85         1  
3    female  35.0      1      0    113803  53.1000         C123         0  
6      male  54.0      0      0     17463  51.8625          E46         0  
10   female   4.0      1      1   PP 9549  16.7000           G6         0  
11   female  58.0      0      0    113783  26.5500         C103         0  
..      ...   ...    ...    ...       ...      ...          ...       ...  
871  female  47.0      1      1     11751  52.5542          D35         0  
872    male  33.0      0      0       695   5.0000  B51 B53 B55         0  
879  female  56.0      0      1     11767  83.1583          C50         1  
887  female  19.0      0      0    112053  30.0000          B42         0  
889    male  26.0      0      0    111369  30.0000         C148         1  

[183 rows x 11 columns]